on:
  workflow_call:
    inputs:
      secrets:
        type: string
        description: Secrets
        required: false
        default: ""

env:
  VAULT_ENDPOINT: http://vault.infrastructure.svc.cluster.local:8200
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  staging:
    name: Staging secrets
    runs-on: self-hosted
    environment:
      name: staging
    steps:
      - name: Fetch Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ env.VAULT_ENDPOINT }}
          githubToken: ${{ env.GH_TOKEN }}
          secrets: |
            infrastructure/data/bndigital/staging/registry          docker-url            | DOCKER_REGISTRY             ;
            infrastructure/data/bndigital/staging/registry          docker-username       | DOCKER_USERNAME             ;
            infrastructure/data/bndigital/staging/registry          docker-password       | DOCKER_PASSWORD             ;
            infrastructure/data/bndigital/staging/kubernetes        cluster               | KUBERNETES_CLUSTER          ;
            infrastructure/data/bndigital/staging/digitalocean      token                 | DIGITALOCEAN_TOKEN          ;
            infrastructure/data/bndigital/staging/spaces            access-key-id         | AWS_ACCESS_KEY_ID           ;
            infrastructure/data/bndigital/staging/spaces            secret-access-key     | AWS_SECRET_ACCESS_KEY       ;
            infrastructure/data/bndigital/staging/spaces            access-key-id         | SPACES_ACCESS_KEY_ID        ;
            infrastructure/data/bndigital/staging/spaces            secret-access-key     | SPACES_SECRET_ACCESS_KEY    ;
            ${{ inputs.secrets }}

      - name: Populate Github secrets
        uses: google/secrets-sync-action@v1.7.0
        with:
          secrets: |
            ^DOCKER_.*
            ^AWS_.*
            ^SPACES_.*
            ^KUBERNETES_.*
            ^DIGITALOCEAN_.*
          repositories: |
            ${{ github.repository_owner }}/${{ github.event.repository.name }}
          dry_run: false
          github_token: ${{ env.GH_TOKEN }}
          concurrency: 10
          
